## Computation ACME-NumpyIntro
### 4. Introduction to NumPy

* #### July 2, 2019
* #### Sherry Tian

### Problem 1 

In [1]:
import numpy as np
A = np.array([[3, -1, 3], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])

In [2]:
np.dot(A, B)

array([[ 28,  17, -30,  -7],
       [-54,  -7,  58,  65]])

In [3]:
A@B

array([[ 28,  17, -30,  -7],
       [-54,  -7,  58,  65]])

### Problem 2

In [4]:
a = np.array([[3,1,4], [1,5,9], [-5,3,1]])

In [5]:
-A**3 + 9*A**2 - 15*A

array([[   9,   25,    9],
       [  -7,   25, 1593]])

> $A^2 = AA$, matrix product not the component-wise square. 
> Check Cayley-Hamilton theorem 

In [6]:
print(A.ndim, A.shape, A.size)
print(a.ndim, a.shape, a.size)

2 (2, 3) 6
2 (3, 3) 9


### Array Creation 

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones((2,5), dtype = np.int)   # array a tuple 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
I = np.eye(2)
I 

array([[1., 0.],
       [0., 1.]])

In [10]:
np.full_like(I, 3)   # same to np.full(I.shape, 3)

array([[3., 3.],
       [3., 3.]])

In [11]:
# upper triangle 
np.triu(a)

# diagonal 
np.diag(a)

array([3, 5, 1])

### Problem 3

In [ ]:
A = 

In [31]:
A = np.ones(7)
A = np.triu(A).astype(np.int64)
A

array([[1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1]])

In [42]:
B = (A.T)
B = B*(-6) + 5
B

array([[-1,  5,  5,  5,  5,  5,  5],
       [-1, -1,  5,  5,  5,  5,  5],
       [-1, -1, -1,  5,  5,  5,  5],
       [-1, -1, -1, -1,  5,  5,  5],
       [-1, -1, -1, -1, -1,  5,  5],
       [-1, -1, -1, -1, -1, -1,  5],
       [-1, -1, -1, -1, -1, -1, -1]])

In [43]:
print("The answer of ABA is: ", A @ B @ A, sep = "\n")

The answer of ABA is: 
[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


### Fancy Indexing 
> using another array as an index

In [14]:
y = np.arange(10,20,2)
y 

array([10, 12, 14, 16, 18])

In [15]:
mask = y > 15 
mask

array([False, False, False,  True,  True])

In [16]:
y[mask] = 100
y

array([ 10,  12,  14, 100, 100])

### Problem 4 

In [17]:
def clear_neg(array): 
    copy = array.copy()
    mask = copy < 0 
    copy[mask] = 0
    return copy 

In [44]:
A = np.array([1, 0, 0, -1, -2, -4, 0, 4, 3, -3])
print(clear_neg(A))

[1 0 0 0 0 0 0 4 3 0]


```
np.ravel()
np.T  or np.transpose()
np.vstack()
or x[:, np.newaxis]
```

> Stacking are all functions! Not attribute 

### Problem 5

In [47]:
A = np.arange(6).reshape((2,3))
B = np.tril(np.ones((3,3)))*3
C = np.eye(3) * (-2)

In [19]:
A_T = A.T
I = np.eye(3)

In [48]:
# stack more zeros to 8*8
z1 = np.zeros((3,3))
z2 = np.zeros((5,2))
z3 = np.zeros((2,3))
col1 = np.vstack((z1,A,B))
col2 = np.vstack((A.T,z2))
col3 = np.vstack((I,z3,C))

np.hstack((col1, col2, col3))

array([[ 0.,  0.,  0.,  0.,  3.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  4.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  2.,  5.,  0.,  0.,  1.],
       [ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  4.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

In [20]:
block = np.concatenate((np.hstack((np.zeros((3,1)), A_T, I))
                        , np.hstack((A, np.zeros((2,3))))
                        , np.hstack((B,C))))
block

array([[ 0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.],
       [ 3.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0., -0., -2., -0.],
       [ 3.,  3.,  3., -0., -0., -2.]])

### Numerical Computing
Always use np instead of math module working with arrays. 

> axis = 0 of each column 

> axis = 1 of each row

In [21]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
np.abs(x)   # np.array([abs(i) for i in x])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.sin(x)   # np.array([math.sin(i) for i in x])

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [24]:
np.exp(3)

20.085536923187668

In [25]:
x.min(axis=0)   # np.array([min(x[:,i]) for i in range(3)])

array([0, 1, 2])

In [26]:
x.sum(axis=1)   # np.array([sum(x[i, :]) for i in range(3)])

array([ 3, 12, 21])

### Problem 6

In [27]:
def row_stochastic(array): 
    check = False
    for x in array.sum(axis=1): 
        if x == 1: 
            check = True
        else: 
            check = False
    return check

In [59]:
def stochastic_row(array): 
    row_sum = array.sum(axis=1)
    result = array / row_sum[:, np.newaxis]
    return result 

In [60]:
stochastic_row(x)

array([[0.        , 0.33333333, 0.66666667],
       [0.25      , 0.33333333, 0.41666667],
       [0.28571429, 0.33333333, 0.38095238]])

### Problem 7

In [54]:
grid = np.load("grid.npy")
for i in range(20): 
    for j in range(17): 
        winner = max(np.prod(grid[i,j:j+4]), winner)
print(winner)

48477312


In [ ]:
###np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])